databases:
  - name: fbclone
    databaseName: fbclone
    user: kingsley

services:
  - type: web
    name: facebook_clone_django_backend
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn backend.wsgi:application"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
        name: fbclone
        property: connectionString
      - key: SECRET_KEY
        generateValue: true
        key: WEB_CONCURRENCY
          value: 4
