# Generated by Django 4.1 on 2022-10-07 19:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_user_friends_user_theme"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="friends",
            field=models.ManyToManyField(
                blank=True, related_name="Friends", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
