# Generated by Django 4.1 on 2022-10-11 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_alter_user_friends"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="cover_image",
            field=models.ImageField(
                blank=True,
                default="images/users/cover/default.png",
                upload_to="images/users/cover",
            ),
        ),
    ]
