# Generated by Django 4.1 on 2022-10-17 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0009_notification_created_at_notification_updated_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="theme",
            field=models.CharField(
                choices=[("dark", "dark"), ("light", "light")],
                default="dark",
                max_length=15,
            ),
        ),
    ]
